### ISSUE TITLE
Compability issue with python 3.11

### ISSUE THREAD

**Issue by FGHaider** [dmarc3/vscode-nastran#17]
Hi, love the extension! There appears to a compability issue with python 3.11, running the following:

- python 3.11
- pygls 1.0.2
- Visual Studio Code 
- vscode-nastran v1.0.1

When hovering over a keyword I get the following error in VSCode:

```
Traceback (most recent call last):
  File "C:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygls\protocol.py", line 270, in _execute_request_callback
    self._send_response(msg_id, result=future.result())
                                       ^^^^^^^^^^^^^^^
  File "c:\Users\abc\.vscode\extensions\mbakke.vscode-nastran-1.0.1\server\server.py", line 120, in hovers
    card = re.match(REGEX_KEY[section], line)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 166, in match
    return _compile(pattern, flags).match(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\re\_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\re\_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\re\_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\re\_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 4
[Error - 6:53:53 PM] Request textDocument/hover failed.
  Message: re.error: global flags not at the start of the expression at position 4
  Code: -32602 
```

Looking at https://docs.python.org/3/library/re.html it appears some changes have been made to the regex library in Python 3.11, could one of these changes be causing the above issue? I.e. the input argument `REGEX_KEY[section]` of the `re.match` call in server.py is no longer valid in 3.11.

**Comment by FGHaider** [comment]
Fix would be to change each regex in [vscode-nastran](https://github.com/dmarc3/vscode-nastran/tree/main)/[syntaxes](https://github.com/dmarc3/vscode-nastran/tree/main/syntaxes)/nastran.json  `"^\\s*(?i)(PATTERN)"` -> `"^(?i)\\s*(PATTERN)"`. Change in python 3.11 regex is that:

**Comment by dmarc3** [comment]
Hey @FGHaider , well written issue and solution in #18. Thanks for the contribution!

I am going to incorporate a few more simple things (`CONTRIBUTING.md` per #16 and a `CODE_OF_CONDUCT.md`) before I push an update to visual studio marketplace. You can expect a v1.0.2 in the next couple days.
